### ISSUE TITLE
Thank you for re-hosting

### ISSUE THREAD

**Issue by jakebesworth** [tanema/M-an.lua#1]
I noticed the original author deleted all their repos and when asked, they didn't give any reason why.

I'd suggest maybe adding the original video (as a gif) in the README to give an idea how the library works.

Also I just hope the library is up to date... I know you might have gotten the source from the love2forums, which hopefully wasn't out of date with the Github.

I added the latest Moan.lua to one of my projects, but I can't find the original file in my git history for some reason, only my revision of it.

**Comment by tanema** [comment]
This is as updated as I could find. I used the most current library from the forums with bug fixes applied, figured out by bug reports on the forums. If you have the gif available still please open a PR adding it to the README.

**Comment by jakebesworth** [comment]
That makes sense, thanks for reviving the library and adding more to it!
